# - name: Check docker status

- name: Create Postgres Container
  docker_container:
    name: "{{ postgres_instance_name }}"
    image: postgres:{{ postgresql_version }}
    state: started
    # recreate: yes
    restart_policy: always
    ports:
      - "{{postgres_instance_port}}:{{postgres_instance_port}}"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - name: minikube
    env:
      POSTGRES_USER: "{{ postgresql_user }}"
      POSTGRES_PASSWORD: "{{ postgresql_password }}"
  register: postgres_container_result

- name: "Add {{ postgres_instance_name }}_ip to /etc/host"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: " {{ postgres_instance_name }}$"
    line: "{{ postgres_container_result.container.NetworkSettings.Networks.minikube.IPAddress }} {{ postgres_instance_name }}"

# Configure PostgreSQL. geerlingguy.postgresql
- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: users_props.yml