- name: "deploy "
  hosts:
    - node1
  gather_facts: true
  become: true
  handlers:
    - import_tasks: handlers/main.yaml
  vars:
      ansible_python_interpreter: /usr/bin/python3.8
  vars_files:
    - vars/main.yaml  
  pre_tasks:
    - import_tasks: tasks/status_docker.yaml
    - import_tasks: tasks/status_minikube.yaml

  roles:
    - name: "docker: Install"
      role: geerlingguy.docker
      when: status_docker.stdout is not search('Docker')
    - name: "docker: Setting"
      role: docker
    - name: "minikube: Install"
      role: robertdebock.minikube
      when: '"host: Running" not in status_minikube.stdout_lines'
    - name: "helm: Install "
      role: geerlingguy.helm
    - name: "postgresql-client: Install"
      role: cimon-io.postgresql-client
    - name: "postgres: Run on docker"
      role: postgresql
    - name: "awx: Deploy on minikube"
      role: awx
    - name: "nginx: Run on docker"
      role: nginx
    
    - name: "vault: Run on docker"
      role: vault
    
    - name: "vector: Run on docker"
      role: vector
    - name: "elastic: Run on docker"
      role: elastic

    - name: ""
      role: post

    - name: "grafana: Run on docker"
      role: grafana

    - name: "keycloak: Run on docker"
      role: keycloak

  post_tasks: 
    - import_tasks: tasks/alias_kubectl.yaml

