- name: Add a repository
  become_user: vagrant
  kubernetes.core.helm_repository:
    name: awx-operator
    repo_url: https://ansible-community.github.io/awx-operator-helm/

- name: Deploy awx chart
  become_user: vagrant
  kubernetes.core.helm:
    name: awx
    chart_ref: awx-operator/awx-operator
    release_namespace: default
    # values_files:
    #   - /path/to/values.yaml