- name: Create Elastic Container
  docker_container:
    name: "{{ kibana_instance_name }}"
    image: "kibana:{{ tag_image }}"
    state: started
    recreate: "{{ kibana_recreate }}"
    # restart_policy: always
    ports:
      - 5601:5601
    networks:
      - name: minikube
        ipv4_address: 192.168.49.8
    env:
      ELASTICSEARCH_HOSTS: http://elastic:9200
      XPACK_APM_SERVICEMAPENABLED: "true"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
      LOGGING_ROOT_LEVEL: info 
  register: kibana_container_result

- name: "Add {{ kibana_instance_name }}_ip to /etc/host"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: " {{ kibana_instance_name }}$"
    line: "{{ kibana_container_result.container.NetworkSettings.Networks.minikube.IPAddress }} {{ kibana_instance_name }}"
