- name: Get INVENTORY_ID 
  ansible.builtin.uri:
    url: "{{ awx_service_url.stdout }}/api/v2/inventories/?name={{ INVENTORY_NAME }}"
    user: "{{ TOWER_USER }}"
    password: "{{ TOWER_PASSWORD }}"
    method: GET
    force_basic_auth: true
    status_code: 200
  register: rc

- name: Defile INVENTORY_ID
  set_fact: 
    INVENTORY_ID: "{{ rc.json.results[0].id }}"


- name: Get credential_types 
  ansible.builtin.uri:
    url: "{{ awx_service_url.stdout }}/api/v2/projects/?name={{ PROJ_NAME }}"
    user: "{{ TOWER_USER }}"
    password: "{{ TOWER_PASSWORD }}"
    method: GET
    force_basic_auth: true
    status_code: 200
  register: rc

- name: Defile INVENTORY_ID
  set_fact: 
    PROJ_ID: "{{ rc.json.results[0].id }}"

- name: GET job_template 
  ansible.builtin.uri:
    url: "{{ awx_service_url.stdout }}/api/v2/job_templates/?name={{ JOB_TMP_NAME }}"
    user: "{{ TOWER_USER }}"
    password: "{{ TOWER_PASSWORD }}"
    method: GET
    force_basic_auth: true
    status_code: 200
    validate_certs: false
    follow_redirects: all
  register: rc

- name: POST job_template 
  ansible.builtin.uri:
    url: "{{ awx_service_url.stdout }}/api/v2/job_templates/"
    user: "{{ TOWER_USER }}"
    password: "{{ TOWER_PASSWORD }}"
    method: POST
    body: "{{ lookup('ansible.builtin.template','files/job_template.json.j2') }}"
    force_basic_auth: true
    status_code: 201
    body_format: json
    validate_certs: false
    follow_redirects: all
  when: rc.json.results[0].id is undefined

- name: PATCH job_template
  ansible.builtin.uri:
    url: "{{ awx_service_url.stdout }}/api/v2/job_templates/{{ rc.json.results[0].id }}"
    user: "{{ TOWER_USER }}"
    password: "{{ TOWER_PASSWORD }}"
    method: PATCH
    body: "{{ lookup('ansible.builtin.template','files/job_template.json.j2') }}"
    force_basic_auth: true
    status_code: 200
    body_format: json
    validate_certs: false
    follow_redirects: all
  when: rc.json.results[0].id is defined
